### ISSUE TITLE
Item Description

### ISSUE THREAD

**Issue by zroberts** [MattGable/ebayfinder#1]
Is it possible to have an item Description handed back as well, or is that not available in the api?

**Comment by MattGable** [comment]
This issue might be choice of API in this case. findItemsByKeywordsResponse output (the current default for this module) does not contain a description, though that functionality would probably be quite useful.
(see "Output" below)
http://developer.ebay.com/devzone/finding/CallRef/findItemsByKeywords.html#expand

Edit: not "choice of API" but "choice of search type" above

**Comment by zroberts** [comment]
I imagine it would be possible by taking the item numbers and performing a second call for each item in the first response to get the description, but that's going outside the scope of the project. Was really just saying that in case you decided you wanted to look into it further after the class is over. 

Thanks for checking in on it though!

**Comment by MattGable** [comment]
Yes, I think (as you mention) several other search types on ebay do have that field--that would indeed be good to have and is probably a better choice that the current findItemsByKeywords. Thanks @zroberts!
